/* Generated by AN DISI Unibo */ 
package it.unibo.ctxdemoreq
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "demorequest.pl", "sysRules.pl","ctxdemoreq"
	)
}

